id: P003287
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:52:48.676058
source_metadata:
  id: bdr:W2CZ8081
  title: ཚིག་མཛོད་བརྡ་དག་ཀུན་གསལ་མེ་ལོང་
  author: ''
  volumes:
    4cabca199ac64f238f837a42a9803451:
      image_group_id: I1PD96750
      title: ''
      volume_number: 1
      total_pages: 628
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
